$SCAN-STOP
$PA-STOP
FRM-SET-PA 0
$WAIT 2
DCMAUTO-OFF
FSEQ-OFF
FSEQ-INIT
$SUBARRAY default.antlist phasecal
$MK_TABLES pcal_tab #1
FSEQ-FILE #2
FSEQ-ON
FEMAUTO-OFF
FEMATTN 0
# Set the Ant 16 FEM attenuation to fixed values for now
HATTN 0 12 ANT16
VATTN 0 12 ANT16
DCMAUTO-ON ant1-16
TRACKTABLE pcal_tab.radec
TRACK ant1-16
RADECOFF 0 10
$PA-TRACK ANT16 #3
$WAIT 15
$SCAN-START
$WAIT 5
DCMTABLE dcm.txt
